# =====================================================
# Zentrale Hardware-Konfiguration für Rock 5B
# Diese Datei dient als Referenz / kann bei Bedarf verwendet werden
# =====================================================

hwdec=rkmpp
vo=gpu
gpu-api=opengl
opengl-es=yes

scale=bilinear
dscale=bilinear
cscale=bilinear
correct-downscaling=no
linear-downscaling=no

dither=no
deband=no
opengl-swapinterval=0

video-sync=display-desync
framedrop=vo
swapchain-depth=8
hwdec-extra-frames=24
vd-lavc-threads=1

secenable=no
input-conf=etc/rock-input.conf
